ktor:
  deployment:
    port: 8080
  application:
    modules:
      - org.bazar.authorization.infrastructure.BazarAuthorizationApplicationKt.module
grpc:
  port: 9090
profile: ${PROFILE:PROD}
db:
  jdbcUrl: ${DB_URL:jdbc:postgresql://localhost:5432/bzrauthz}
  user: ${DB_USER:postgres}
  password: ${DB_PASS:postgres}
  logSqlQueries: false
  runMigrations: true

auth:
  issuer: ${KC_ISSUER_URL:http://localhost:9999/realms/bazar-realm}
  jwkUrl: ${KC_JWK_URL:http://localhost:9999/realms/bazar-realm/protocol/openid-connect/certs}
  realm: "bazar-realm"
  audience: ${KC_AUDIENCE:bazar-authorization}

cerbos:
  url: ${CERBOS_URL:localhost:3593}
logging:
  level:
    root: INFO
    org:
      bazar: ${LOGGING_LEVEL:INFO}